In [1]:
import math
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
train = pd.read_csv('train_set.csv')
test = pd.read_csv('../data/test.csv')

In [4]:
train.shape, test.shape

((1756, 81), (1459, 80))

In [5]:
dtypes = train.dtypes
category_columns = dtypes[lambda x: x == 'object']

In [6]:
train['source'] = 'train'
test['source'] = 'test'
data = pd.concat([train, test], ignore_index=True)
data.shape

(3215, 82)

In [7]:
data.apply(lambda x: sum(x.isnull()))[lambda x: x > 0]

Alley           2987
BsmtCond          93
BsmtExposure      94
BsmtFinSF1         1
BsmtFinSF2         1
BsmtFinType1      90
BsmtFinType2      90
BsmtFullBath       3
BsmtHalfBath       3
BsmtQual          92
BsmtUnfSF          1
Exterior1st        1
Exterior2nd        1
Fence           2595
FireplaceQu     1576
Functional         2
GarageArea         1
GarageCars         1
GarageCond       175
GarageFinish     175
GarageQual       175
GarageType       172
GarageYrBlt      175
KitchenQual        1
LotFrontage      514
MSZoning           4
MasVnrArea        32
MasVnrType        33
MiscFeature     3099
PoolQC          3205
SalePrice       1459
SaleType           1
TotalBsmtSF        1
Utilities          2
dtype: int64

In [8]:
for category_column in category_columns.keys():
    print('\nFrequency count for variable {0}'.format(category_column))
    print(data[category_column].value_counts())
    
    not_na_elements = len(data[category_column].dropna().values)
    na_elements = len(data[category_column]) - not_na_elements
    print('Total: {0} of which {1} are not a number'.format(not_na_elements, na_elements))

Frequency count for variable MSZoning
RL         2471
RM          527
FV          155
C (all)      31
RH           26
A (agr)       1
Name: MSZoning, dtype: int64
Total: 3211 of which 4 are not a number

Frequency count for variable Street
Pave    3201
Grvl      14
Name: Street, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Alley
Grvl    145
Pave     83
Name: Alley, dtype: int64
Total: 228 of which 2987 are not a number

Frequency count for variable LotShape
Reg    2056
IR1    1062
IR2      82
IR3      15
Name: LotShape, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable LandContour
Lvl    2888
HLS     151
Bnk     121
Low      55
Name: LandContour, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Utilities
AllPub    3212
NoSewr       1
Name: Utilities, dtype: int64
Total: 3213 of which 2 are not a number

Frequency count for variable LotConfig
Inside     2352
Corner      556
CulDSac     197
FR2          93
FR3          17
Name: LotConfig, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable LandSlope
Gtl    3064
Mod     140
Sev      11
Name: LandSlope, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Neighborhood
NAmes      489
OldTown    271
CollgCr    269
Edwards    218
Somerst    202
NridgHt    201
Gilbert    181
Sawyer     168
SawyerW    138
NWAmes     136
Mitchel    134
BrkSide    111
IDOTRR     110
Crawfor    107
Timber      76
NoRidge     68
StoneBr     58
SWISU       55
MeadowV     46
ClearCr     38
BrDale      32
NPkVill     30
Veenker     28
Blmngtn     25
Blueste     16
Greens       6
GrnHill      2
Name: Neighborhood, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Condition1
Norm      2759
Feedr      176
Artery     106
RRAn        50
PosN        49
RRAe        31
PosA        25
RRNn        11
RRNe         8
Name: Condition1, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Condition2
Norm      3180
Feedr       15
Artery       8
PosA         6
PosN         4
RRNn         1
RRAn         1
Name: Condition2, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable BldgType
1Fam      2648
TwnhsE     267
Duplex     120
Twnhs      115
2fmCon      65
Name: BldgType, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable HouseStyle
1Story    1623
2Story     948
1.5Fin     360
SLvl       135
SFoyer      98
2.5Unf      25
1.5Unf      19
2.5Fin       7
Name: HouseStyle, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable RoofStyle
Gable      2558
Hip         606
Gambrel      20
Flat         18
Mansard       9
Shed          4
Name: RoofStyle, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable RoofMatl
CompShg    3175
Tar&Grv      23
WdShake       8
WdShngl       6
Membran       1
Roll          1
Metal         1
Name: RoofMatl, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Exterior1st
VinylSd    1119
MetalSd     501
HdBoard     488
Wd Sdng     462
Plywood     250
CemntBd     139
BrkFace      88
WdShing      64
AsbShng      49
Stucco       41
BrkComm       8
CBlock        2
AsphShn       2
Stone         1
Name: Exterior1st, dtype: int64
Total: 3214 of which 1 are not a number

Frequency count for variable Exterior2nd
VinylSd    1111
MetalSd     504
Wd Sdng     446
HdBoard     441
Plywood     296
CmentBd     140
Wd Shng      91
BrkFace      48
Stucco       47
AsbShng      40
Brk Cmn      30
ImStucc      13
CBlock        3
Stone         2
AsphShn       2
Name: Exterior2nd, dtype: int64
Total: 3214 of which 1 are not a number

Frequency count for variable MasVnrType
None       1924
BrkFace     958
Stone       272
BrkCmn       27
CBlock        1
Name: MasVnrType, dtype: int64
Total: 3182 of which 33 are not a number

Frequency count for variable ExterQual
TA    1978
Gd    1075
Ex     122
Fa      40
Name: ExterQual, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable ExterCond
TA    2780
Gd     326
Fa      87
Ex      18
Po       4
Name: ExterCond, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Foundation
PConc     1438
CBlock    1369
BrkTil     337
Slab        57
Stone        8
Wood         6
Name: Foundation, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable BsmtQual
TA    1425
Gd    1290
Ex     301
Fa     106
Po       1
Name: BsmtQual, dtype: int64
Total: 3123 of which 92 are not a number

Frequency count for variable BsmtCond
TA    2875
Gd     123
Fa     118
Po       5
Ex       1
Name: BsmtCond, dtype: int64
Total: 3122 of which 93 are not a number

Frequency count for variable BsmtExposure
No    2094
Av     451
Gd     313
Mn     263
Name: BsmtExposure, dtype: int64
Total: 3121 of which 94 are not a number

Frequency count for variable BsmtFinType1
GLQ    929
Unf    928
ALQ    488
Rec    311
BLQ    286
LwQ    183
Name: BsmtFinType1, dtype: int64
Total: 3125 of which 90 are not a number

Frequency count for variable BsmtFinType2
Unf    2737
Rec     109
LwQ      93
BLQ      80
ALQ      65
GLQ      41
Name: BsmtFinType2, dtype: int64
Total: 3125 of which 90 are not a number

Frequency count for variable Heating
GasA     3178
GasW       21
Grav        9
Wall        5
OthW        1
Floor       1
Name: Heating, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable HeatingQC
Ex    1636
TA     944
Gd     522
Fa     111
Po       2
Name: HeatingQC, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable CentralAir
Y    2995
N     220
Name: CentralAir, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable Electrical
SBrkr    2945
FuseA     209
FuseF      50
FuseP      10
Mix         1
Name: Electrical, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable KitchenQual
TA    1666
Gd    1236
Ex     241
Fa      70
Po       1
Name: KitchenQual, dtype: int64
Total: 3214 of which 1 are not a number

Frequency count for variable Functional
Typ     2990
Min2      85
Min1      70
Mod       43
Maj1      12
Maj2      10
Sev        2
Sal        1
Name: Functional, dtype: int64
Total: 3213 of which 2 are not a number

Frequency count for variable FireplaceQu
Gd    816
TA    634
Fa     87
Po     56
Ex     46
Name: FireplaceQu, dtype: int64
Total: 1639 of which 1576 are not a number

Frequency count for variable GarageType
Attchd     1901
Detchd      850
BuiltIn     207
Basment      40
2Types       31
CarPort      14
Name: GarageType, dtype: int64
Total: 3043 of which 172 are not a number

Frequency count for variable GarageFinish
Unf    1359
RFn     887
Fin     794
Name: GarageFinish, dtype: int64
Total: 3040 of which 175 are not a number

Frequency count for variable GarageQual
TA    2865
Fa     141
Gd      26
Po       6
Ex       2
Name: GarageQual, dtype: int64
Total: 3040 of which 175 are not a number

Frequency count for variable GarageCond
TA    2920
Fa      87
Po      15
Gd      15
Ex       3
Name: GarageCond, dtype: int64
Total: 3040 of which 175 are not a number

Frequency count for variable PavedDrive
Y    2889
N     262
P      64
Name: PavedDrive, dtype: int64
Total: 3215 of which 0 are not a number

Frequency count for variable PoolQC
Gd    4
Ex    3
Fa    2
TA    1
Name: PoolQC, dtype: int64
Total: 10 of which 3205 are not a number

Frequency count for variable Fence
MnPrv    361
GdPrv    125
GdWo     123
MnWw      11
Name: Fence, dtype: int64
Total: 620 of which 2595 are not a number

Frequency count for variable MiscFeature
Shed    107
Gar2      4
Othr      4
TenC      1
Name: MiscFeature, dtype: int64
Total: 116 of which 3099 are not a number

Frequency count for variable SaleType
WD       1520
WD       1258
New       257
COD        99
ConLD      33
CWD        15
ConLw      10
Oth         9
ConLI       7
Con         6
Name: SaleType, dtype: int64
Total: 3214 of which 1 are not a number

Frequency count for variable SaleCondition
Normal     2648
Partial     263
Abnorml     203
Family       57
Alloca       28
AdjLand      16
Name: SaleCondition, dtype: int64
Total: 3215 of which 0 are not a number

In [9]:
data = pd.get_dummies(data)
data = data.fillna(data[:data.shape[0]].mean())
data.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,EnclosedPorch,...,SaleType_New,SaleType_Oth,SaleType_WD,SaleType_WD,Street_Grvl,Street_Pave,Utilities_AllPub,Utilities_NoSewr,source_test,source_train
0,1059,0,0,3,773.0,0.0,1.0,0.0,286.0,0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
1,2492,0,0,2,2146.0,0.0,1.0,0.0,346.0,0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
2,1008,0,0,2,643.0,0.0,1.0,0.0,365.0,0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
3,1214,0,0,2,0.0,0.0,0.0,0.0,1214.0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,832,384,0,2,442.0,0.0,0.0,0.0,390.0,102,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0

In [10]:
prices = data['SalePrice']

data.drop('SalePrice',axis=1,inplace=True)
data = pd.concat([data, prices], axis=1)

In [11]:
train = data.loc[data['source_train'] == 1]
test = data.loc[data['source_test'] == 1]

In [12]:
train.drop('source_test',axis=1,inplace=True)
train.drop('source_train',axis=1,inplace=True)

test.drop('source_test',axis=1,inplace=True)
test.drop('source_train',axis=1,inplace=True)
test.drop('SalePrice',axis=1,inplace=True)

/Users/mabounassif/miniconda3/envs/udem/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/mabounassif/miniconda3/envs/udem/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/mabounassif/miniconda3/envs/udem/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/mabounassif/miniconda3/envs/udem/lib/python3.5/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/mabounassif/miniconda3/envs/udem/lib/python3.5/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [13]:
train.to_csv('train_modified.csv', index=False)
test.to_csv('test_modified.csv', index=False)